import nodemailer from "nodemailer";
import { MongoClient } from "mongodb";

export async function POST(req) {
  try {
    const data = await req.json();

    // Save to MongoDB
    const client = await MongoClient.connect(process.env.MONGODB_URI);
    const db = client.db("travel_agency");
    await db.collection("enquiries").insertOne(data);

    // Extract fields
    const {
      firstName,
      lastName,
      email,
      phone,
      message,
      selectedServices = [],
      details = {},
    } = data;

    // 🔹 Generate structured email body (HTML)
    const htmlBody = `
      <h2>🧳 New Travel Enquiry Received</h2>
      <h3>👤 Personal Details</h3>
      <p><strong>Name:</strong> ${firstName} ${lastName}</p>
      <p><strong>Email:</strong> ${email}</p>
      <p><strong>Phone:</strong> ${phone}</p>
      <p><strong>Message:</strong> ${message || "—"}</p>
      <hr />

      <h3>🧭 Selected Services</h3>
      <ul>
        ${selectedServices.map((s) => `<li>${s}</li>`).join("")}
      </ul>

      <hr />
      <h3>📋 Service Details</h3>
      ${Object.entries(details)
        .filter(([_, val]) => Object.keys(val).length > 0)
        .map(
          ([service, info]) => `
          <h4 style="color:#0a66c2; text-transform:capitalize;">${service}</h4>
          <table border="1" cellspacing="0" cellpadding="6" style="border-collapse:collapse; margin-bottom: 1em;">
            ${Object.entries(info)
              .map(
                ([key, value]) => `
              <tr>
                <td><strong>${key.replace(/([A-Z])/g, " $1")}</strong></td>
                <td>${value}</td>
              </tr>`
              )
              .join("")}
          </table>
        `
        )
        .join("")}

      <p style="font-size:0.9em; color:#666;">This message was automatically generated by the Travel Enquiry Form.</p>
    `;

    // 🔹 Plain text fallback (for older clients)
    const textBody = `
New Travel Enquiry

Personal Details
-----------------
Name: ${firstName} ${lastName}
Email: ${email}
Phone: ${phone}
Message: ${message || "-"}

Selected Services:
${selectedServices.join(", ")}

Service Details:
${Object.entries(details)
  .filter(([_, val]) => Object.keys(val).length > 0)
  .map(
    ([service, info]) =>
      `\n${service.toUpperCase()}:\n${Object.entries(info)
        .map(([key, value]) => `  - ${key}: ${value}`)
        .join("\n")}`
  )
  .join("\n")}
    `;

    // Send Email
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS,
      },
    });

    await transporter.sendMail({
      from: "Travel Agency Enquiries",
      to: "kripzenthings@gmail.com",
      subject: `✈️ New Travel Enquiry from ${firstName} ${lastName}`,
      text: textBody,
      html: htmlBody,
    });

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error("❌ Enquiry Email Error:", err);
    return new Response(JSON.stringify({ error: "Internal Server Error" }), {
      status: 500,
    });
  }
}
