import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"], 
  weight: [ "500"], 
  style: ["normal", "italic"],       
});

export const metadata = {
  title: "Pacific Internationals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cormorant.className}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
